// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dnnkaisqhlbxnalbjbev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRubmthaXNxaGxieG5hbGJqYmV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzOTg4NTcsImV4cCI6MjA1OTk3NDg1N30.-6P9rCu7blA9hOL7S1r156WQ46Wmg_6G3qhLgQBytgE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);